#!/usr/bin/env zsh

# Description: Executes Ansible playbook for local setup.
#
# Dependencies: confirm
#   https://github.com/ggustafsson/Kjell/blob/master/src/confirm
#
# Usage: maint-ansible
#
# Author: Göran Gustafsson <gustafsson.g@gmail.com>
# License: BSD 3-Clause

case $HOST in
  Onett)
    playbook=setup_macos_home.yml
    ;;
  Twoson)
    git_pull=1
    playbook=setup_macos_work.yml
    ;;
  *)
    echo "Could not determine which Ansible playbook to use! Exiting..."
    exit 1
esac

dir=~/Projects/Ansiblebot

if [[ $git_pull -eq 1 ]]; then
  print -P "%B%F{cyan}git pull @ ${dir/$HOME/~}:%f%b"
  git -C $dir pull
  echo
fi

print -P "%B%F{cyan}ansible-playbook $playbook:%f%b"
confirm || exit 1
cd $dir
ansible-playbook $playbook --ask-become || exit $?
