#!/usr/bin/env zsh

# Description: Executes a bunch of maintenance commands I run regularly.
#
# Usage: maint
#
# Author: Göran Gustafsson <gustafsson.g@gmail.com>
# License: BSD 3-Clause

if [[ $HOST == Onett ]]; then
  choices=(
    1 "maint-ansible" on
    2 "rmhogs"        on
    3 "backup"        on
    4 "gitpl"         off
  )
else
  choices=(
    1 "maint-ansible" on
    2 "rmhogs"        on
    3 "backup"        off
    4 "gitpl"         on
  )
fi

selections=$(dialog \
  --default-button "Cancel" \
  --checklist "Select maintenance commands..." 0 40 0 \
  $choices 2>&1 > /dev/tty)

clear

for selection in ${(z)selections}; do
  case $selection in
    1)
      echo
      maint-ansible
      ;;
    2)
      echo
      rmhogs
      ;;
    3)
      echo
      backup --yes
      ;;
    4)
      echo
      gitpl
      ;;
  esac

  if [[ $? -ne 0 ]]; then
    notify Maintenance 'Job failed!'
    echo "Maintenance job failed! Exiting..."
    exit 1
  fi
done

if [[ -n $selections ]]; then
  notify Maintenance 'Finished running!'
fi
