#!/usr/bin/env zsh

# Description: Deletes all ".DS_Store" files recursively.
#
# Usage: rmds
#        rmds <path>
#
# Author: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

if [[ $# -eq 0 ]]; then
  find . -type f -name .DS_Store -delete -print
elif [[ $# -eq 1 ]]; then
  find $1 -type f -name .DS_Store -delete -print
else
  echo "Usage: ${0:t} [PATH]..."
fi
