#!/usr/bin/env zsh

# Description: Deletes various space hogging files/directories and unused
# Docker container images.
#
# Usage: rmhogs
#
# Author: Göran Gustafsson <gustafsson.g@gmail.com>
# License: BSD 3-Clause

rm_objects=(
  ~/Library/Caches/Homebrew
  ~/Library/Caches/com.apple.dt.Xcode/Downloads
  ~/Library/Logs/Homebrew
  ~/Library/Mail\ Downloads
  ~/Library/iTunes/iPad\ Software\ Updates
  ~/Library/iTunes/iPhone\ Software\ Updates
)

echo "Removing space hogging files..."

for object in $rm_objects; do
  if [[ -a $object ]]; then
    echo
    rm -rfv $object
  fi
done

if [[ -S /var/run/docker.sock ]]; then
  echo "\nRemoving dangling Docker images...\n"
  docker image prune --force
fi
