#!/usr/bin/env zsh

# Description: Pretty prints ANSI escape sequence of first 16 terminal colors
# and additional style attributes.
#
# Usage: 16col
#
# Author: Göran Gustafsson <gustafsson.g@gmail.com>
# License: BSD 3-Clause

function color {
  printf "\e[${1}m %-4s \e[0m " "${1}m"
}

# Foreground colors.
for i in {30..37}; do
  color $i
done && echo
# Bright foreground colors.
for i in {90..97}; do
  color $i
done && echo

# Background colors.
for i in {40..47}; do
  color $i
done && echo
# Same with black foreground.
for i in {40..47}; do
  echo -n "\e[30m"
  color $i
done && echo

# Bright background colors.
for i in {100..107}; do
  color $i
done && echo
# Same with black foreground.
for i in {100..107}; do
  echo -n "\e[30m"
  color $i
done && echo

echo '
Escape    = \\e[  \\033[  \\x1B[
Reset     = \\e[0m
\e[1mBold\e[0m      = \\e[1m
\e[3mItalic\e[0m    = \\e[3m
\e[4mUnderline\e[0m = \\e[4m
\e[5mBlinking\e[0m  = \\e[5m
\e[7mReverse\e[0m   = \\e[7m'
