#!/usr/bin/env zsh

# Description: Pretty prints all 256 terminal colors.
#
# Usage: 256colors
#
# Author: Göran Gustafsson <gustafsson.g@gmail.com>
# License: BSD 3-Clause

reset="\e[0m"

for num in {0..255}; do
  fg="\e[0;38;5;${num}m"
  bg="\e[30;48;5;${num}m"

  printf "$bg Color %-3s $reset ${fg}Color ${num}$reset\n" $num
done
