#!/usr/bin/env zsh

# Description: Pretty prints all 256 terminal colors. Handy when making color
# schemes for Vim etc.
#
# Usage: 256col
#
# Author: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

rst="\e[0m"

for code in {0..255}; do
  fg="\e[0;38;5;${code}m"
  bg="\e[30;48;5;${code}m"

  printf "$bg Color %-3s $rst ${fg}Color ${code}$rst\n" $code
done
