#!/usr/bin/env zsh

# Description: Pretty prints all 256 terminal colors.
#
# Usage: 256col
#
# Author: Göran Gustafsson <gustafsson.g@gmail.com>
# License: BSD 3-Clause

rst="\e[0m"

for i in {0..255}; do
  fg="\e[0;38;5;${i}m"
  bg="\e[30;48;5;${i}m"

  printf "$bg Color %-3s $rst ${fg}Color ${i}$rst\n" $i
done
