#!/usr/bin/env zsh

# Description: Select bookmark with Fzf and go to directory. Bookmarks are
# symbolic links in ~/.config/nnn/bookmarks, or ~/.bookmarks as fallback.
#
# Dependencies: fzf
#
# ~/.zshrc:
#
#   alias cdb="source cdb"
#
# Usage: cdb
#
# Author: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

cdb_nnn=${XDG_CONFIG_HOME:-$HOME/.config}/nnn/bookmarks
if [[ -d $cdb_nnn ]]; then
  cdb_dir=$cdb_nnn
elif [[ -d ~/.bookmarks ]]; then
  cdb_dir=~/.bookmarks
else
  echo "Failed to find bookmarks directory! Exiting..."
  return 1
fi

cdb_sel=$(\ls "$cdb_dir" | fzf --tac)
if [[ -z $cdb_sel ]]; then
  return 1
fi

cdb_dst=$(readlink "$cdb_dir/$cdb_sel") # Destination of symbolic link.
echo $cdb_dst
cd -- "$cdb_dst"

# Be nice and clean up before leaving...
unset cdb_dir cdb_dst cdb_nnn cdb_sel
