#!/usr/bin/env zsh

# Description: Like "cd .." but on steroids. Current directory is changed to
# closest directory matching pattern.
#
# Example:
#
#   /Users/GLEG/Development/Python $ cdj Us
#   /Users $
#
# ~/.zshrc:
#
#   alias cdj="source cdj"
#
# Usage: cdj <pattern>
#
# Original: https://github.com/vigneshwaranr/bd/blob/master/bd
#
# Author: Göran Gustafsson <gustafsson.g@gmail.com>
# License: BSD 3-Clause

if [[ $# -eq 1 ]]; then
  cdj_dir=$(echo $PWD | sed 's|\(.*/'$1'[^/]*/\).*|\1|')
  if [[ $cdj_dir != $PWD ]]; then
    cd -- "$cdj_dir"
  else
    echo "No match found!"
  fi
  unset cdj_dir
else
  echo "Usage: ${0:t} [PATTERN]..."
fi
