#!/usr/bin/env zsh

# Description: Quickly open up new Markdown file in Nvim with date + arguments
# in filename, e.g. "~/Documents/Text/Notes/2022-08-04 cURL Things.md"
#
# Usage: n <title>
#
# Author: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

if [[ $# -lt 1 ]]; then
  echo "Usage: ${0:t} [TITLE]..."
  exit 1
fi

dir=~/Documents/Text/Notes
date=$(date +%F) # YYYY-MM-DD

nvim "$dir/$date - $*.md"
