#!/usr/bin/env zsh

# Description: Surf the web like it is 1999 with Lynx and DuckDuckGo.
#
# Usage: s
#        s <query>
#
# Author: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

url=https://lite.duckduckgo.com/lite

if [[ $# -ge 1 ]]; then
  input=$*
  query=${input// /+} # Replace spaces with "+" for valid URL.
  url="$url\?q=$query"
fi

lynx $browser $url
