#!/usr/bin/env zsh

# Description: Combines "ask" and "cht" for use in Tmux popup window.
#
# ~/.tmux.conf:
#
#   bind Enter menu -T "#[align=centre] Launcher " \
#     "Open Cheat" c "popup -EE -h 60% -w 60% tmux-cht"
#
# Dependencies: ask & cht
#
#   https://github.com/ggustafsson/Kjell/blob/master/src/ask
#   https://github.com/ggustafsson/Kjell/blob/master/src/cht
#
# Usage: tmux-cht
#
# Author: Göran Gustafsson <gustafsson.g@gmail.com>
# License: BSD 3-Clause

title="Enter cheat.sh query..."
input=$(ask $title)

if [[ -n $input ]]; then
  cht $input
else
  exit 1
fi
