#!/usr/bin/env zsh

# Description: Nvim equivalent of Vim's "view" with some additional settings.
# Using script instead of alias to allow for usage in Tmux and other scripts.
#
# Dependencies: nvim
#
# Usage: view
#        view <path>
#
# Author: Göran Gustafsson <gustafsson.g@gmail.com>
# License: BSD 3-Clause

nvim \
  -R \
  -c "lua vim.diagnostic.disable()" \
  -c "set nolist nonumber norelativenumber" \
  -c "nmap q <Cmd>q<CR>" \
  $*
